

POST http://localhost:5000/upload-csv HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/csv


< ${workspaceFolder}/test.csv
--boundary--

### new request


GET http://localhost:5000/download-csv HTTP/1.1
Accept: text/csv